/**
 * FallbackComps — Static Snapshot (Set 16: Lore & Legends)
 *
 * VERIFIED: All unit names here match either:
 *   - TFTSet16 display_name from CDragon tftchampions-teamplanner.json, OR
 *   - TFTSet4_Act2 display_name (for Choncc mode)
 *
 * TFTSet16 Full Champion List (100 champs, from CDragon verified):
 * Aatrox, Ahri, Ambessa, Anivia, Annie, Aphelios, Ashe, Aurelion Sol,
 * Azir, Bard, Baron Nashor, Bel'Veth, Blitzcrank, Braum, Briar, Brock,
 * Caitlyn, Cho'Gath, Darius, Diana, Dr. Mundo, Draven, Ekko, Fiddlesticks,
 * Fizz, Galio, Gangplank, Garen, Graves, Gwen, Illaoi, Jarvan IV, Jhin,
 * Jinx, Kai'Sa, Kalista, Kennen, Kindred, Kobuko & Yuumi, Kog'Maw, LeBlanc,
 * Leona, Lissandra, Loris, Lucian & Senna, Lulu, Lux, Malzahar, Mel, Milio,
 * Miss Fortune, Nasus, Nautilus, Neeko, Nidalee, Orianna, Ornn, Poppy,
 * Qiyana, Rek'Sai, Renekton, Rift Herald, Rumble, Ryze, Sejuani, Seraphine,
 * Sett, Shen, Shyvana, Singed, Sion, Skarner, Sona, Swain, Sylas, T-Hex,
 * Tahm Kench, Taric, Teemo, Thresh, Tristana, Tryndamere, Twisted Fate, Vayne,
 * Veigar, Vi, Viego, Volibear, Warwick, Wukong, Xerath, Xin Zhao, Yasuo,
 * Yone, Yorick, Yunara, Zaahen, Ziggs, Zilean, Zoe
 */
import { type CompData } from '../store/appStore'

export const FALLBACK_COMPS: CompData[] = [
  // ─── SET 16 / RANKED ──────────────────────────────────
  {
    id: 's16-1',
    name: 'Conqueror Ambessa',
    tier: 'S',
    avgPlace: 2.8,
    playRate: 15.2,
    gameMode: 'Ranked',
    traits: ['Conqueror', 'Firelight'],
    units: [
      { name: 'Ambessa',    cost: 4, items: [{ name: 'Bloodthirster' }, { name: 'Titan\'s Resolve' }, { name: 'Hand of Justice' }] },
      { name: 'Ekko',       cost: 4, items: [{ name: 'Ionic Spark' }, { name: 'Warmog\'s Armor' }] },
      { name: 'Vi',         cost: 4, items: [{ name: 'Sterak\'s Gage' }] },
      { name: 'Warwick',    cost: 2, items: [] },
      { name: 'Sett',       cost: 3, items: [] },
      { name: 'Darius',     cost: 1, items: [] },
      { name: 'Garen',      cost: 1, items: [] },
      { name: 'Sion',       cost: 5, items: [] },
    ],
  },
  {
    id: 's16-2',
    name: 'Rebel Jinx',
    tier: 'S',
    avgPlace: 3.1,
    playRate: 12.5,
    gameMode: 'Ranked',
    traits: ['Rebel', 'Artillerist'],
    units: [
      { name: 'Jinx',      cost: 5, items: [{ name: 'Infinity Edge' }, { name: 'Last Whisper' }, { name: 'Giant Slayer' }] },
      { name: 'Tristana',  cost: 2, items: [{ name: 'Bloodthirster' }, { name: 'Guinsoo\'s Rageblade' }] },
      { name: 'Rumble',    cost: 5, items: [{ name: 'Warmog\'s Armor' }, { name: 'Bramble Vest' }] },
      { name: 'Illaoi',    cost: 4, items: [{ name: 'Gargoyle Stoneplate' }] },
      { name: 'Zoe',       cost: 4, items: [{ name: 'Blue Buff' }, { name: 'Jeweled Gauntlet' }] },
      { name: 'Veigar',    cost: 3, items: [] },
      { name: 'Sion',      cost: 5, items: [] },
    ],
  },
  {
    id: 's16-3',
    name: 'Black Rose LeBlanc',
    tier: 'A',
    avgPlace: 3.9,
    playRate: 9.4,
    gameMode: 'Ranked',
    traits: ['Black Rose', 'Sorcerer'],
    units: [
      { name: 'LeBlanc',    cost: 5, items: [{ name: 'Spear of Shojin' }, { name: 'Archangel\'s Staff' }] },
      { name: 'Sion',       cost: 5, items: [{ name: 'Warmog\'s Armor' }, { name: 'Dragon\'s Claw' }, { name: 'Gargoyle Stoneplate' }] },
      { name: 'Swain',      cost: 3, items: [] },
      { name: 'Lissandra',  cost: 3, items: [{ name: 'Blue Buff' }, { name: 'Jeweled Gauntlet' }] },
      { name: 'Darius',     cost: 1, items: [] },
      { name: 'Elise',      cost: 2, items: [] },
      { name: 'Vladimir',   cost: 5, items: [{ name: 'Morellonomicon' }] },
    ],
  },
  {
    id: 's16-4',
    name: 'Enforcer Caitlyn',
    tier: 'A',
    avgPlace: 3.8,
    playRate: 7.2,
    gameMode: 'Ranked',
    traits: ['Enforcer', 'Sniper'],
    units: [
      { name: 'Caitlyn',   cost: 5, items: [{ name: 'Infinity Edge' }, { name: 'Last Whisper' }, { name: 'Giant Slayer' }] },
      { name: 'Vi',        cost: 4, items: [{ name: 'Titan\'s Resolve' }, { name: 'Sterak\'s Gage' }] },
      { name: 'Loris',     cost: 3, items: [] },
      { name: 'Blitzcrank',cost: 2, items: [] },
      { name: 'Garen',     cost: 1, items: [] },
      { name: 'Braum',     cost: 2, items: [] },
      { name: 'Leona',     cost: 4, items: [] },
    ],
  },
  {
    id: 's16-5',
    name: 'Family Fast 8',
    tier: 'A',
    avgPlace: 3.6,
    playRate: 10.5,
    gameMode: 'Ranked',
    traits: ['Family', 'Pit Fighter'],
    units: [
      { name: 'Jinx',      cost: 5, items: [{ name: 'Bloodthirster' }, { name: 'Infinity Edge' }, { name: 'Last Whisper' }] },
      { name: 'Vi',        cost: 4, items: [{ name: 'Titan\'s Resolve' }, { name: 'Sterak\'s Gage' }] },
      { name: 'Ekko',      cost: 4, items: [] },
      { name: 'Ambessa',   cost: 4, items: [] },
      { name: 'Sion',      cost: 5, items: [] },
      { name: 'Darius',    cost: 1, items: [] },
      { name: 'Garen',     cost: 1, items: [] },
    ],
  },
  {
    id: 's16-6',
    name: 'Experiment HyperRoll',
    tier: 'S',
    avgPlace: 2.5,
    playRate: 8.8,
    gameMode: 'HyperRoll',
    traits: ['Experiment', 'Bruiser'],
    units: [
      { name: 'Dr. Mundo',  cost: 4, items: [{ name: 'Dragon\'s Claw' }, { name: 'Warmog\'s Armor' }] },
      { name: 'Lucian & Senna', cost: 3, items: [{ name: 'Blue Buff' }, { name: 'Gunblade' }] },
      { name: 'Lulu',       cost: 2, items: [] },
      { name: 'Blitzcrank', cost: 2, items: [] },
      { name: 'Cho\'Gath',  cost: 4, items: [] },
      { name: 'Sion',       cost: 5, items: [] },
    ],
  },
  // ─── SET 4.5 / CHONCC MODE ────────────────────────────
  {
    id: 's45-1',
    name: 'Elderwood Aurelion Sol',
    tier: 'S',
    avgPlace: 2.4,
    playRate: 12.0,
    gameMode: 'Choncc',
    traits: ['Elderwood', 'Mage'],
    units: [
      { name: 'Aurelion Sol', cost: 4, items: [{ name: 'Jeweled Gauntlet' }, { name: 'Infinity Edge' }] },
      { name: 'Xayah',        cost: 4, items: [{ name: 'Hand of Justice' }] },
      { name: 'Ornn',         cost: 5, items: [{ name: 'Warmog\'s Armor' }, { name: 'Bramble Vest' }] },
      { name: 'Lulu',         cost: 2, items: [] },
      { name: 'Veigar',       cost: 3, items: [{ name: 'Blue Buff' }] },
      { name: 'Nunu',         cost: 3, items: [] },
      { name: 'Maokai',       cost: 1, items: [] },
    ],
  },
  {
    id: 's45-2',
    name: 'Warlord Katarina',
    tier: 'S',
    avgPlace: 2.1,
    playRate: 14.5,
    gameMode: 'Choncc',
    traits: ['Warlord', 'Assassin'],
    units: [
      { name: 'Katarina',  cost: 3, items: [{ name: 'Hextech Gunblade' }, { name: 'Titan\'s Resolve' }] },
      { name: 'Tryndamere', cost: 4, items: [{ name: 'Infinity Edge' }] },
      { name: 'Azir',      cost: 5, items: [{ name: 'Spear of Shojin' }] },
      { name: 'Jarvan IV', cost: 3, items: [{ name: 'Warmog\'s Armor' }] },
      { name: 'Nidalee',   cost: 1, items: [] },
      { name: 'Garen',     cost: 1, items: [] },
    ],
  },
]
